### PR TITLE
Add testing against Python 3.9

### PR DESCRIPTION
**Pull request by miketheman**
I'm trying this library on Python 3.9, and specifically interested in the `issubtype()` call - I haven't found a good alternative anywhere.

It's failing on a call to `issubclass()` with `typing.Optional` - so I wanted to see if the tests would pass here on Python 3.9 before digging deeper.

### CODE REVIEW

**Comment by miketheman** [comment]
Turns out these don't perform any tests at all, the result is always 0 tests pass.

**Comment by bojiang** [comment]
> Turns out these don't perform any tests at all, the result is always 0 tests pass.

Fixed. Thanks!

**Comment by miketheman** [comment]
I rebased, and am able to [show a failure](https://github.com/bojiang/typing_utils/pull/1/checks?check_run_id=2279169714#step:5:101) on Python 3.9, specific to ForwardRefs.

**Comment by miketheman** [comment]
[This function](https://github.com/bojiang/typing_utils/blob/0d7251ad9521d01efa429655eb100753c4c4882a/typing_utils/__init__.py#L141-L147) needs an update for Python 3.9.

**Pull request merged**
